# Generated by Django 2.2.1 on 2019-05-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20190518_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='updated_at',
        ),
    ]
